spring:
  kafka:
#    listener.concurrency: 8
    bootstrap-servers: localhost:9093
    properties:
      security:
        protocol: "SSL"
      ssl.endpoint.identification.algorithm: ""
    ssl:
      protocol: "SSL"
      keyStoreLocation: "file:///C:/ ... / location of kafka.keystore.jks"
      keyStorePassword: "put it here"
      trustStoreLocation: "file:///C:/ ... / location of kafka.truststore.jks"
      trustStorePassword: "put it here"
      keyPassword: "put it here"
    consumer:
      auto-offset-reset: earliest
      group-id: dosomething
    producer:
      max-request-size: 3145728
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server.port: 8080
