spring:
  kafka:
#    listener.concurrency: 8 # if you want multiple of these microservices running
    bootstrap-servers: localhost:9093
    properties:
      security.protocol: "SSL"
      ssl.endpoint.identification.algorithm: ""
    ssl:
      keyStoreLocation: "file:///C:/ ... / location of kafka.keystore.jks"
      keyStorePassword: "put it here"
      trustStoreLocation: "file:///C:/ .. / location of kafka.truststore.jks"
      trustStorePassword: "put it here"
      keyPassword: "put it here"
    consumer:
      auto-offset-reset: earliest
      group-id: cplusplus
    producer:
      max-request-size: 3145728
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082
